import type { BaseballProvider } from "./BaseballProvider";

interface MlbGame { gameDate:string; status:{abstractGameState:string;detailedState:string}; teams:{away:{team:{name:string};score?:number};home:{team:{name:string};score?:number}}; venue?:{name:string} }
interface MlbSchedule { dates?: Array<{games:MlbGame[]}> }
interface MlbStandings { records?: Array<{division?:{id:number;name?:string};teamRecords:Array<{team:{name:string};wins:number;losses:number;winningPercentage:string}>}> }
interface MlbLeader { person?:{fullName:string}; team?:{name:string}; value:string|number }
interface MlbLeaders { leagueLeaders?: Array<{leaderCategory:string;leaders:MlbLeader[]}> }
// 球団名は固定辞書で正確な日本語表記を維持する
const teamJa:Record<string,string>={
"Arizona Diamondbacks":"アリゾナ・ダイヤモンドバックス","Athletics":"アスレチックス","Atlanta Braves":"アトランタ・ブレーブス","Baltimore Orioles":"ボルチモア・オリオールズ","Boston Red Sox":"ボストン・レッドソックス","Chicago Cubs":"シカゴ・カブス","Chicago White Sox":"シカゴ・ホワイトソックス","Cincinnati Reds":"シンシナティ・レッズ","Cleveland Guardians":"クリーブランド・ガーディアンズ","Colorado Rockies":"コロラド・ロッキーズ","Detroit Tigers":"デトロイト・タイガース","Houston Astros":"ヒューストン・アストロズ","Kansas City Royals":"カンザスシティ・ロイヤルズ","Los Angeles Angels":"ロサンゼルス・エンゼルス","Los Angeles Dodgers":"ロサンゼルス・ドジャース","Miami Marlins":"マイアミ・マーリンズ","Milwaukee Brewers":"ミルウォーキー・ブルワーズ","Minnesota Twins":"ミネソタ・ツインズ","New York Mets":"ニューヨーク・メッツ","New York Yankees":"ニューヨーク・ヤンキース","Philadelphia Phillies":"フィラデルフィア・フィリーズ","Pittsburgh Pirates":"ピッツバーグ・パイレーツ","San Diego Padres":"サンディエゴ・パドレス","San Francisco Giants":"サンフランシスコ・ジャイアンツ","Seattle Mariners":"シアトル・マリナーズ","St. Louis Cardinals":"セントルイス・カージナルス","Tampa Bay Rays":"タンパベイ・レイズ","Texas Rangers":"テキサス・レンジャーズ","Toronto Blue Jays":"トロント・ブルージェイズ","Washington Nationals":"ワシントン・ナショナルズ"};
// 確認済み選手名のみ日本語化し、未登録名は公式英語名へフォールバックする
const playerJa:Record<string,string>={
"Yordan Alvarez":"ヨルダン・アルバレス","Kyle Schwarber":"カイル・シュワーバー","Hunter Goodman":"ハンター・グッドマン","Ben Rice":"ベン・ライス","James Wood":"ジェームズ・ウッド","Junior Caminero":"ジュニオール・カミネロ","CJ Abrams":"CJ・エイブラムズ","Matt Olson":"マット・オルソン","Byron Buxton":"バイロン・バクストン","Colson Montgomery":"コルソン・モンゴメリー","Kazuma Okamoto":"岡本 和真","Otto Lopez":"オット・ロペス","Luis Arraez":"ルイス・アラエス","Nick Gonzales":"ニック・ゴンザレス","Jung Hoo Lee":"イ・ジョンフ","Freddie Freeman":"フレディ・フリーマン","Yandy Díaz":"ヤンディ・ディアス","Michael Harris II":"マイケル・ハリス2世","TJ Rumfield":"TJ・ラムフィールド","Jake McCarthy":"ジェイク・マッカーシー","Jacob Misiorowski":"ジェイコブ・ミジオロウスキー","Cam Schlittler":"キャム・シュリトラー","Chris Sale":"クリス・セール","Chase Burns":"チェイス・バーンズ","Nick Martinez":"ニック・マルティネス","Dylan Cease":"ディラン・シース","Parker Messick":"パーカー・メシック","Justin Wrobleski":"ジャスティン・ロブレスキー","Eduardo Rodriguez":"エドゥアルド・ロドリゲス","Max Meyer":"マックス・マイヤー"};
const divisionJa:Record<number,string>={200:"ア・リーグ西地区",201:"ア・リーグ東地区",202:"ア・リーグ中地区",203:"ナ・リーグ西地区",204:"ナ・リーグ東地区",205:"ナ・リーグ中地区"};
const teamName=(name:string)=>teamJa[name]||name;
const playerName=(name:string)=>playerJa[name]||name;

// MLB公式Stats APIからキー不要で当日情報とランキングを取得するProvider
export class MlbStatsProvider implements BaseballProvider {
  private formatDate(date:Date){return new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Tokyo",month:"2-digit",day:"2-digit",year:"numeric"}).format(date);}
  private season(){return Number(new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Tokyo",year:"numeric"}).format(new Date()));}
  private async officialJson<T>(url:string):Promise<T>{const response=await fetch(url,{headers:{Accept:"application/json","User-Agent":"BASEBALL-COMPASS/1.0"},cf:{cacheTtl:900,cacheEverything:true}});if(!response.ok)throw new Error(`MLB Stats API: ${response.status}`);return response.json() as Promise<T>;}
  private async games(date:Date){const url=`https://statsapi.mlb.com/api/v1/schedule?sportId=1&date=${encodeURIComponent(this.formatDate(date))}&hydrate=team,linescore`;const json=await this.officialJson<MlbSchedule>(url);return(json.dates?.flatMap(item=>item.games)||[]).map(game=>{const played=game.status.abstractGameState==="Final"||game.status.abstractGameState==="Live";return{away:teamName(game.teams.away.team.name),home:teamName(game.teams.home.team.name),time:new Intl.DateTimeFormat("ja-JP",{timeZone:"Asia/Tokyo",hour:"2-digit",minute:"2-digit",hour12:false}).format(new Date(game.gameDate)),venue:game.venue?.name||"会場未定",status:game.status.detailedState,score:played?`${game.teams.away.score??0} - ${game.teams.home.score??0}`:undefined};});}
  async getToday(){const games=await this.games(new Date());return{date:new Intl.DateTimeFormat("ja-JP",{timeZone:"Asia/Tokyo",dateStyle:"full"}).format(new Date()),league:"MLB",games,officialLinks:[{label:"NPB公式 試合日程・結果",url:"https://npb.jp/games/"},{label:"MLB公式 Scores",url:"https://www.mlb.com/scores"}]};}
  async getSchedule(){const now=new Date(),yesterday=new Date(now.getTime()-86400000);return{today:await this.games(now),yesterday:await this.games(yesterday),officialLinks:[{label:"NPB公式 試合日程・結果",url:"https://npb.jp/games/"},{label:"MLB公式 Scores",url:"https://www.mlb.com/scores"}]};}
  async getRanking(){
    const season=this.season();
    const standingsUrl=`https://statsapi.mlb.com/api/v1/standings?leagueId=103,104&season=${season}&standingsTypes=regularSeason&hydrate=team`;
    const hittingUrl=`https://statsapi.mlb.com/api/v1/stats/leaders?leaderCategories=homeRuns,battingAverage,runsBattedIn,hits,stolenBases,onBasePercentage,sluggingPercentage,onBasePlusSlugging&statGroup=hitting&statType=season&season=${season}&sportId=1&limit=10&hydrate=person,team`;
    const pitchingUrl=`https://statsapi.mlb.com/api/v1/stats/leaders?leaderCategories=earnedRunAverage,wins,strikeouts,saves,walksAndHitsPerInningPitched,winningPercentage&statGroup=pitching&statType=season&season=${season}&sportId=1&limit=10&hydrate=person,team`;
    const [standingsData,hittingData,pitchingData]=await Promise.all([this.officialJson<MlbStandings>(standingsUrl),this.officialJson<MlbLeaders>(hittingUrl),this.officialJson<MlbLeaders>(pitchingUrl)]);
    const standings=(standingsData.records||[]).flatMap(record=>record.teamRecords.map((team,index)=>({division:divisionJa[record.division?.id||0]||"MLB",rank:index+1,name:teamName(team.team.name),value:`${team.wins}勝 ${team.losses}敗（${team.winningPercentage}）`})));
    const groups=[...(hittingData.leagueLeaders||[]),...(pitchingData.leagueLeaders||[])];
    const rows=(category:string,suffix:string)=>groups.find(group=>group.leaderCategory===category)?.leaders.map(leader=>({name:`${playerName(leader.person?.fullName||"-")}${leader.team?.name?`｜${teamName(leader.team.name)}`:""}`,value:`${leader.value}${suffix}`}))||[];
    const battingLeaders=[{key:"homeRuns",label:"ホームラン",unit:"本"},{key:"battingAverage",label:"打率",unit:""},{key:"runsBattedIn",label:"打点",unit:"点"},{key:"hits",label:"安打",unit:"本"},{key:"stolenBases",label:"盗塁",unit:""},{key:"onBasePercentage",label:"出塁率",unit:""},{key:"sluggingPercentage",label:"長打率",unit:""},{key:"onBasePlusSlugging",label:"OPS",unit:""}].map(metric=>({...metric,rows:rows(metric.key,metric.unit)}));
    const pitchingLeaders=[{key:"earnedRunAverage",label:"防御率",unit:""},{key:"wins",label:"勝利",unit:"勝"},{key:"strikeouts",label:"奪三振",unit:""},{key:"saves",label:"セーブ",unit:"S"},{key:"walksAndHitsPerInningPitched",label:"WHIP",unit:""},{key:"winPercentage",label:"勝率",unit:""}].map(metric=>({...metric,rows:rows(metric.key,metric.unit)}));
    return{standings,battingLeaders,pitchingLeaders,homeRuns:rows("homeRuns","本"),batting:rows("battingAverage",""),era:rows("earnedRunAverage","")};
  }
  async getShop(){return{products:[{id:"bat-01",category:"バット",name:"コンパス メイプルバット",description:"振り抜きやすさを重視した硬式木製モデル。",price:14800},{id:"glove-01",category:"グローブ",name:"オールラウンドグローブ",description:"扱いやすいエントリーモデル。",price:12800},{id:"spike-01",category:"スパイク",name:"フィールドスピード",description:"軽量性とグリップを両立。",price:9800},{id:"train-01",category:"トレーニング",name:"トレーニングバンド",description:"肩まわりのウォームアップに。",price:2400},{id:"gear-01",category:"練習器具",name:"バッティングティー",description:"高さ調節ができる自主練習用。",price:6900},{id:"pick-01",category:"おすすめ",name:"ベースボールスターターセット",description:"練習を始める人におすすめ。",price:19800}]};}
}